name: ollama/SCA Scan

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'The Docker image to scan'
        required: true
        default: 'ollama/ollama'

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull the Docker image
        run: docker pull ${{ github.event.inputs.docker_image }}

      - name: Run Docker Scout Scan
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,compare,sbom
          image: ${{ github.event.inputs.docker_image }}
          sarif-file: scout_scan.sarif

      - name: Upload SARIF file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: scout_scan.sarif
          path: scout_scan.sarif

      - name: Upload SARIF file to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scout_scan.sarif
          category: Security/Ollama
